Enable Cognito access to Elasticsearch database
cisagov/cool-dns-dmarc-import pull request #11
Opened 2023-12-22 22:04 UTC by dav3r

#  #

## 🗣 Description ##

This PR leverages the changes in https://github.com/cisagov/dmarc-import-tf-module/pull/49 to set up Cognito access to Elasticsearch via Terraform.  It also enables creation/deletion of Cognito users with Terraform.

## 💭 Motivation and context ##

Cognito resources and access were previously configured manually, so this is an improvement.

I marked this PR as `blocked` since it should be merged immediately after https://github.com/cisagov/dmarc-import-tf-module/pull/49.

## 🧪 Testing ##

I tested this by targeting Terraform applies in Production ([using this branch of `cisagov/dmarc-import-tf-module`](https://github.com/cisagov/dmarc-import-tf-module/tree/improvement/add-cognito)) until everything applied correctly.  After that, I created and deleted test users until I was satisfied that everything was working as intended. 

I confirmed that my Cognito user was able to sign up using the temporary password that is generated, create an MFA token, login to the ~Elasticsearch~ Open Search dashboard, and query for some data.

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [x] All relevant type-of-change labels have been added.
- [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [x] All relevant repo and/or project documentation has been updated
      to reflect the changes in this PR.
- [x] All new and existing tests pass.

2023-12-27 18:30 UTC, jsf9k approved these changes

2024-01-03 15:21 UTC, jasonodoom approved these changes

2024-01-18 17:13 UTC, mcdonnnj requested changes

2024-01-18 17:13 UTC, mcdonnnj commented on variables.tf
> +  description = "The domain to use for the Cognito endpoint. For custom domains, this is the fully-qualified domain name, such as auth.example.com. For Amazon Cognito prefix domains, this is the pref
Just to prevent misreading the prefix as `auth.`.

```suggestion
  description = "The domain to use for the Cognito endpoint. For custom domains, this is the fully-qualified domain name, such as \"auth.example.com\". For Amazon Cognito prefix domains, this is the prefix alone, such as \"auth\"."
```

2024-01-18 17:13 UTC, mcdonnnj commented on README.md
> +| cognito\_user\_pool\_domain | The domain to use for the Cognito endpoint. For custom domains, this is the fully-qualified domain name, such as auth.example.com. For Amazon Cognito prefix domains, t
```suggestion
| cognito\_user\_pool\_domain | The domain to use for the Cognito endpoint. For custom domains, this is the fully-qualified domain name, such as "auth.example.com". For Amazon Cognito prefix domains, this is the prefix alone, such as "auth". | `string` | `"dmarc-import"` | no |
```

2024-01-18 17:13 UTC, mcdonnnj commented on dmarc_import.tf
> +  temporary_bucket_name           = var.temporary_bucket_name
I'm assuming we want to pass through the `opensearch_service_role_for_auth_name` variable?

```suggestion
  aws_region                            = var.aws_region
  cognito_authenticated_role_name       = var.cognito_authenticated_role_name
  cognito_identity_pool_name            = var.cognito_identity_pool_name
  cognito_user_pool_client_name         = var.cognito_user_pool_client_name
  cognito_user_pool_domain              = var.cognito_user_pool_domain
  cognito_user_pool_name                = var.cognito_user_pool_name
  cognito_usernames                     = var.cognito_usernames
  elasticsearch_domain_name             = var.elasticsearch_domain_name
  elasticsearch_index                   = var.elasticsearch_index
  elasticsearch_type                    = var.elasticsearch_type
  emails                                = var.emails
  lambda_function_name                  = var.lambda_function_name
  lambda_function_zip_file              = var.lambda_function_zip_file
  opensearch_service_role_for_auth_name = var.opensearch_service_role_for_auth_name
  permanent_bucket_name                 = var.permanent_bucket_name
  queue_name                            = var.queue_name
  rule_set_name                         = var.rule_set_name
  temporary_bucket_name                 = var.temporary_bucket_name
```

2024-01-19 21:16 UTC, dav3r commented on variables.tf
> +  description = "The domain to use for the Cognito endpoint. For custom domains, this is the fully-qualified domain name, such as auth.example.com. For Amazon Cognito prefix domains, this is the pref
@mcdonnnj Just highlighting the fact that for consistency, I edited your suggestions slightly to also put quotes around the example domain, in addition to the example prefix, as you suggested (see https://github.com/cisagov/cool-dns-dmarc-import/pull/11/commits/f69725646cd667b5d73c4bdd418e6a2391a3dee6).

2024-01-19 21:20 UTC, dav3r commented on dmarc_import.tf
> +  temporary_bucket_name           = var.temporary_bucket_name
Yes, great catch, thanks!

2024-01-29 20:04 UTC, mcdonnnj approved these changes
LGTM ✔

2024-01-29 20:28 UTC, merged